create extension if not exists pgcrypto;

create table if not exists public.monitors (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('CD', 'LP')),
  artist text not null,
  album text not null,
  edition text,
  site text not null check (site in ('Medimops', 'Momox')),
  url text not null,
  target_price numeric(10,2) not null check (target_price > 0),
  current_price numeric(10,2),
  last_checked_at timestamptz,
  last_status text default 'never_checked' check (last_status in ('never_checked', 'ok', 'below_target', 'error')),
  last_error text,
  alert_email text,
  alert_sent boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  alert_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.settings (id, alert_email)
values (1, null)
on conflict (id) do nothing;

create table if not exists public.price_checks (
  id bigint generated by default as identity primary key,
  monitor_id uuid not null references public.monitors(id) on delete cascade,
  checked_at timestamptz not null default now(),
  price numeric(10,2),
  status text not null check (status in ('never_checked', 'ok', 'below_target', 'error')),
  error text,
  source text
);

create index if not exists monitors_artist_idx on public.monitors (artist);
create index if not exists monitors_album_idx on public.monitors (album);
create index if not exists monitors_active_idx on public.monitors (is_active);
create index if not exists price_checks_monitor_checked_idx on public.price_checks (monitor_id, checked_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists monitors_set_updated_at on public.monitors;
create trigger monitors_set_updated_at
before update on public.monitors
for each row execute function public.set_updated_at();

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

-- Uso personale: l'app accede a Supabase solo lato server con service role key.
-- Per semplicità RLS resta disabilitata. Non esporre mai SUPABASE_SERVICE_ROLE_KEY nel browser.
alter table public.monitors disable row level security;
alter table public.settings disable row level security;
alter table public.price_checks disable row level security;
